[package]
name = "pr21"
version = "0.1.0"
edition = "2021"

[dependencies]
xjbutil = { version="0.9.0-DELTA", default-features=false, features=[
    "either",
    "zvec",
    "void"
] }
smallvec = "1"

[dev-dependencies]
variant_count = "1.1.0"

[[bin]]
name = "pr21"
path = "src/bin/main.rs"
